camera:
  ros__parameters:
    port: 5600
    distortion_model: "plumb_bob"
    frame:
      height: 1080
      width: 1920
    camera_matrix:
      [1901.104339, 0.000000, 960.0,
       0.000000, 1901.104339, 540.0,
       0.000000, 0.000000, 1.000000]

    distortion_coefficients:
      [0.0, -0.0, -0.0, -0.0, 0.000000]
    projection_matrix:
      [1922.307861, 0.000000, 1094.456021, 0.000000,
       0.000000, 1818.110962, 75.192440, 0.000000,
       0.000000, 0.000000, 1.000000, 0.000000]

qualisys_mocap:
  ros__parameters:
    ip: "192.168.254.1"
    port: 22223
    version: "1.22"
    body: "bluerov"

qualisys_localizer:
  ros__parameters:
    update_rate: 30.0
    body: "bluerov" # This should be the same as the body parameter setting for the qualisys_mocap node

gazebo_localizer:
  ros__parameters:
    update_rate: 30.0
    gazebo_odom_topic: "/model/bluerov2_heavy/odometry"
